This is the mobile version of my portfolio website which contains  my detail.
degisew/Portfolio pull request #2
Opened 2022-07-02 15:56 UTC by degisew

2022-07-02 17:08 UTC, 1GORDON requested changes
##
## Hi @degisew. ✋

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- Good commit messages  ✔️ 
- Professional Readme ✔️
- Linters are passing ✔️
- Usage of Semantic tags ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 17:08 UTC, 1GORDON commented on css/style.css
> +}
Great job @degisew 👏

- [ ] Please implement the button interactions specified in the project requirements. The hover and enable effects as provided in the Figma design
- Figma button interactions
![button interactions](https://user-images.githubusercontent.com/63917725/177009596-56d4d918-4aa2-4380-9072-c9e2504cf55c.PNG)

2022-07-02 17:08 UTC, 1GORDON commented on html/index.html
> +    <!-- </div> -->
Great job @degisew 👏

- [ ] You may please remove all the commented code from your project as this is not a good practice.

2022-07-02 17:08 UTC, 1GORDON commented on css/style.css
> +  /* border: 1px solid #6070FF; */
Great work @degisew 👏

- [ ] You may please remove all the commented code from your style sheet.

2022-07-02 18:17 UTC, degisew commented
@1GORDON  I don't understand the required changes and now I can't finish it because there is no power here. It is night time

2022-07-05 09:09 UTC, codecaiine approved these changes
Hi @degisew , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
:heavy_check_mark: Good use of gitflow
:heavy_check_mark: Comments are meaningful
:heavy_check_mark: Great PR description
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-05 11:33 UTC, merged

2022-07-12 07:26 UTC, AmitKlohan reviewed
Hi @digisew 

you may consider my suggestions in the comment

2022-07-12 07:26 UTC, AmitKlohan commented on html/index.html
> +    </section>
Hi @degisew 
You've done great work so far

Suggestion 

I suggest to add a footer in last section to make this more semantic

2022-07-12 07:39 UTC, teke85 commented on html/index.html
> +        <p>
@degisew Great job so far!! I suggest you use an H1 tag as opposed to using a p tag as per the HTML Semantics tags, and HTML and CSS best practices.

2022-07-12 08:32 UTC, scientistsagoemarcus reviewed
Good job so far, you can still work harder.