Desktop version
degisew/Portfolio pull request #5
Opened 2022-07-14 17:18 UTC by degisew

This is  a Desktop version of a portfolio website

2022-07-15 06:48 UTC, muneebulrehman requested changes
Hi @degisew , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors
- Good commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-15 06:48 UTC, muneebulrehman commented on css/desktop.css
> +  height: 4100px;
Consider removing the width and height. Setting the width is leaving a lot of white space on screens large than 1390px and it also removes the scalability of your app beyond 1390px, so essentially the width of your app is fixed to 1390px no matter the size of the desktop display. Also, the height needs not to be set since it depends on the height of content and is dynamically calculated.
![image](https://user-images.githubusercontent.com/33268927/179166253-89a4f977-cd64-4e65-9b22-778333eeffc7.png)

2022-07-15 06:48 UTC, muneebulrehman commented on html/index.html
>        <ul class="skills">
Consider using actual text instead of images. As you can see, this portion is distorted compared to Figma design.
![image](https://user-images.githubusercontent.com/33268927/179166586-ff85f069-24b0-418c-b995-fcb8733f610e.png)

2022-07-15 06:48 UTC, muneebulrehman commented on html/index.html
> +  <link rel="stylesheet" href="../css/desktop.css" media="(min-width:768px)"/>
Your whole mobile layout is breaking at this point. Consider fixing it and then submit it for re-review.
![image](https://user-images.githubusercontent.com/33268927/179167309-d11a9719-246c-4f21-b31e-56458147dfb1.png)

2022-07-16 00:20 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/93039359/178569876-9fcda5e8-6819-4569-95ee-acb393903a05.jpg)

### Hey @degisew :wave:

### Highlights :1st_place_medal:

:heavy_check_mark: Following Linters 
:heavy_check_mark: Following GitHub Flow


Good job on implementing the project requirements but there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-16 00:20 UTC, HAMMAS-SALEEM commented on css/style.css
>  }
### Your Cards
![margin-right (copy)](https://user-images.githubusercontent.com/93039359/179326028-c66f7e56-7d01-43d8-a670-19744b7311c2.png)

- [ ] You have margin-left great :+1: But please add margin-right to make your card in the center :blush:
- [ ] Please add some **padding-bottom** to make your card look similar to the Figma template :+1:

2022-07-16 00:20 UTC, HAMMAS-SALEEM commented on html/index.html
> +        </li>
### Your About Me Section
![images-to-heading (copy)](https://user-images.githubusercontent.com/93039359/179326392-f41c6742-4b34-4dbd-83c4-1dd358c32c3f.png)

- [ ] Please use `h3` tag to create **Languages**, **Frameworks**, and **Skills** heading instead of using images :+1:

2022-07-16 00:20 UTC, HAMMAS-SALEEM commented on html/index.html
> +        </form>
### Your Contact Me Section
![contact-center](https://user-images.githubusercontent.com/93039359/179326474-1ad6012b-e134-44dc-8ca0-0a8aaeef1273.png)


**[Optional]**
- [ ] It would be nice if you make you make your form in the center. :+1: to follow the Figma template. :blush:

2022-07-16 08:15 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @degisew 

Your project is complete! Great job for making all the requested changes🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Validations correctly implemented
- desktop design followed
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

![tufoin](https://media.giphy.com/media/8Iv5lqKwKsZ2g/giphy.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-16 08:15 UTC, tufoinnkuo10 commented on html/index.html
> +          <input type="submit" name="Get-it-Touch-btn" value="Get it Touch" class="get-it-touch-btn" />
- [optional] please kindly centralize the submit so it looks like the figma version

2022-07-16 08:15 UTC, tufoinnkuo10 commented on html/index.html
> +            love to help with it.
- [optional] great job for centralizing the contact form as demanded by the previous reviewer. Please kindly add the text size and heading, input width, so it looks like the figma design

2022-07-16 08:30 UTC, merged